name: Generate PDFs from Markdown

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y texlive-xetex pandoc fonts-liberation

    - name: Find all Markdown files and convert to PDF
      run: |
        mkdir -p pdf
        for file in $(find . -name '*.md'); do
          filename=$(basename -- "$file")
          pandoc "$file" --pdf-engine=xelatex \
            -V mainfont="Liberation Serif" \
            -o "pdf/${filename%.md}.pdf"
        done

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add pdf/*.pdf
        git commit -m "Add generated PDF files"
        git push origin master

    - name: Upload PDFs
      uses: actions/upload-artifact@v3
      with:
        name: pdfs
        path: 'pdf/*.pdf'
